name: Backport
on:
  pull_request:
    types: [closed, labeled]

jobs:
  backport:
    runs-on: ubuntu-20.04
    name: Backport
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate_token
        with:
          app_id: ${{ secrets.ATOTI_GITHUB_APP_ID }}
          private_key: ${{ secrets.ATOTI_GITHUB_APP_PRIVATE_KEY }}
      - uses: tibdex/backport@v1
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
